version: '3.8'

services:

  backend:
    depends_on:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8080:8080"

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.100.27
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
      - "8081:8081"

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
      MONGO_INITDB_DATABASE: dota
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'root'
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_BASICAUTH_USERNAME: 'sa'
      ME_CONFIG_BASICAUTH_PASSWORD: 'sa'
    depends_on:
      - mongo
    ports:
      - "8082:8082"   

volumes:
  mongo_data:
