ARG PYTHON_VERSION=3.8-slim

FROM python:${PYTHON_VERSION}

RUN pip install pipenv

ENV PIPENV_VENV_IN_PROJECT=1

WORKDIR /usr/src/app

RUN apt-get update \
    && apt-get install -y libgl1-mesa-glx \
    && apt-get purge -y --auto-remove \
    && rm -rf /var/lib/apt/lists/*

COPY Pipfile* /usr/src/app/

RUN pipenv install --deploy --ignore-pipfile

COPY . /usr/src/app/

EXPOSE 8000

CMD ["pipenv", "run", "uvicorn", "main:app", "--host", "0.0.0.0"]


